const actionTypes = {
    SET_CATEGOTY: "SET_CATEGORY",
    ADD_TO_CART: "ADD_TO_CART",
    DELETE_FROM_CART: "DELETE_FROM_CART",
    SET_QUANTITY: "SET_QUANTITY",
    SET_DETAILS_PRODUCT: 'SET_DETAILS_PRODUCT',
}
export default actionTypes